# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Python 3.9.2
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.2
      - name: Run Python commands
        run: |
          pip install --upgrade pipy
          python 3.9.2 -m venv venv
          source env/bin/activate
          echo "VIRTUAL ENV:" $VIRTUAL_ENV
